"""user creds uniqueness improvements

Revision ID: 0ccd68752d0b
Revises: 6068653987bd
Create Date: 2025-09-27 17:15:56.201176

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ccd68752d0b"
down_revision: Union[str, Sequence[str], None] = "6068653987bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_name_key"), "users", type_="unique")
    op.create_unique_constraint("name_and_email_uc", "users", ["name", "email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_and_email_uc", "users", type_="unique")
    op.create_unique_constraint(op.f("users_name_key"), "users", ["name"], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
